DROP DATABASE IF EXISTS GESTIÓN_BANCARIA;
CREATE DATABASE GESTIÓN_BANCARIA CHARACTER SET utf8mb4;
USE GESTIÓN_BANCARIA;

CREATE TABLE CLIENTE (
IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
DNI VARCHAR (9) NOT NULL UNIQUE,
APELLIDO1 VARCHAR (30) NOT NULL,
APELLIDO2 VARCHAR (30),
NOMBRE VARCHAR (30) NOT NULL,
DOMICILIO VARCHAR (100),
TELÉFONO VARCHAR (20) NOT NULL
) AUTO_INCREMENT = 1001;

CREATE TABLE CUENTA (
IDCLIENTE INT,
IDCUENTA VARCHAR(5) PRIMARY KEY,
SALDO DECIMAL (15,2),
MONEDA VARCHAR (20),
FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
ON UPDATE CASCADE ON DELETE CASCADE
);